/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-03-17 22:46:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class VistaHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>ManagerFitness</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/grid.css\" type=\"text/css\" media=\"screen\">\r\n");
      out.write("<script src=\"js/jquery-1.6.3.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/tabs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page1\">\r\n");
      out.write("<div class=\"bg\">\r\n");
      out.write("  <header>\r\n");
      out.write("    <div class=\"menu-row\">\r\n");
      out.write("      <div class=\"main\">\r\n");
      out.write("        <nav>\r\n");
      out.write("          <ul class=\"menu wrapper\">\r\n");
      out.write("            <li><a class=\"active\" href=\"VistaHome.jsp\">Cliente</a></li>\r\n");
      out.write("            <li><a href=\"VistaEventos.jsp\">Actualidad</a></li>\r\n");
      out.write("            <li><a href=\"VistaAdministrador.jsp\">Administrador</a></li>\r\n");
      out.write("            <li><a href=\"VistaEntrenador.jsp\">Entrenador</a></li>\r\n");
      out.write("            <li><a href=\"VistaSugerencias.jsp\">Sugerencias</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("      <div class=\"wrapper p3\">\r\n");
      out.write("        <h1><a href=\"VistaHome.jsp\">ManagerFitness</a></h1>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"tabs\">\r\n");
      out.write("      <li><a href=\"#tab1\">Manager Fitness</a></li>\r\n");
      out.write("      <li><a href=\"#tab2\">Tus Rutinas y Dietas </a></li>\r\n");
      out.write("      <li><a href=\"#tab3\">Conoce Tu Proceso</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"tab_container\">\r\n");
      out.write("      <div id=\"tab1\" class=\"tab_content\">\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("            <figure class=\"img-indent-r\"><img src=\"images/page1-img1.jpg\" alt=\"\"></figure>\r\n");
      out.write("            <div class=\"extra-wrap\">\r\n");
      out.write("              <div class=\"indent\"> <strong class=\"title\">TU MEJOR OPCIÓN</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"tab2\" class=\"tab_content\">\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("            <figure class=\"img-indent-r\"><img src=\"images/page1-img2.jpg\" alt=\"\"></figure>\r\n");
      out.write("            <div class=\"extra-wrap\">\r\n");
      out.write("              <div class=\"indent\"> <strong class=\"title\">Ejercicio y Dieta</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"tab3\" class=\"tab_content\">\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("          <div class=\"wrapper\">\r\n");
      out.write("            <figure class=\"img-indent-r\"><img src=\"images/page1-img3.jpg\" alt=\"\"></figure>\r\n");
      out.write("            <div class=\"extra-wrap\">\r\n");
      out.write("              <div class=\"indent\"> <strong class=\"title\">Qué Has Logrado</strong>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <section id=\"content\">\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("      <div class=\"container_12\">\r\n");
      out.write("      \r\n");
      out.write("        <article class=\"grid_8\">\r\n");
      out.write("            <h2 class=\"img-indent-right\" >MEMBRECIAS!!</h2>\r\n");
      out.write("            <div class=\"wrapper prev-indent-bot\">\r\n");
      out.write("              <figure class=\"img-indent-right\" ><img src=\"images/page1-img4.jpg\" alt=\"\"></figure>\r\n");
      out.write("              <div class=\"extra-wrap\">\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("      \r\n");
      out.write("        <div class=\"wrapper margin-bot\">\r\n");
      out.write("        <form action=\"MembreciaControlador\" method=\"get\">\r\n");
      out.write("          <article class=\"grid_4\">\r\n");
      out.write("            <h3>Principiante</h3>\r\n");
      out.write("            <ul class=\"list-1 img-indent-bot\">\r\n");
      out.write("              <a>INCLUYE </a>\r\n");
      out.write("              <li><a>Asesoría </a></li>\r\n");
      out.write("              <li><a>Médico </a></li>\r\n");
      out.write("              <li><a>1 Hora Diaria </a></li>\r\n");
      out.write("              <li><a>Nutricionista </a></li>\r\n");
      out.write("              <a>$80.000 </a>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <span class=\"text-form\"></span><span class=\"buttons\">\r\n");
      out.write("               <button type=\"submit\" name=\"formulario\" value=\"comprarPrincipiante\" class=\"button-2\"> Comprar </button>\r\n");
      out.write("            </span>\r\n");
      out.write("            </article>\r\n");
      out.write("           <article class=\"grid_4\">\r\n");
      out.write("            <h3>Practicante</h3>\r\n");
      out.write("            <ul class=\"list-1 img-indent-bot\">\r\n");
      out.write("              <a>INCLUYE </a>\r\n");
      out.write("              <li><a>Entrenador Personal </a></li>\r\n");
      out.write("              <li><a>Medico </a></li>\r\n");
      out.write("              <li><a>3 Horas Diarias </a></li>\r\n");
      out.write("              <li><a>Nutricionista </a></li>\r\n");
      out.write("              <li><a>Hidratacion </a></li>\r\n");
      out.write("              <a>$90.000 </a>\r\n");
      out.write("            </ul>\r\n");
      out.write("             <span class=\"text-form\"></span><span class=\"buttons\">\r\n");
      out.write("               <button type=\"submit\" name=\"formulario\" value=\"comprarPracticante\" class=\"button-2\"> Comprar </button>\r\n");
      out.write("            </span>\r\n");
      out.write("            </article>\r\n");
      out.write("            <article class=\"grid_4\">\r\n");
      out.write("            <h3>Animalex</h3>\r\n");
      out.write("            <ul class=\"list-1 img-indent-bot\">\r\n");
      out.write("              <a>INCLUYE</a>\r\n");
      out.write("              <li><a>Medico </a></li>\r\n");
      out.write("              <li><a>6 Horas Diarias </a></li>\r\n");
      out.write("              <li><a>Eventos Gratuitos </a></li>\r\n");
      out.write("              <li><a>Entrenador Personal</a></li>\r\n");
      out.write("              <li><a>Hidratacion </a></li>\r\n");
      out.write("              <a>$120.000 </a>\r\n");
      out.write("            </ul>\r\n");
      out.write("             <span class=\"text-form\"></span><span class=\"buttons\">\r\n");
      out.write("               <button type=\"submit\" name=\"formulario\" value=\"comprarAnimalex\" class=\"button-2\"> Comprar </button>\r\n");
      out.write("            </span>\r\n");
      out.write("            </article>\r\n");
      out.write("            </form>\r\n");
      out.write("          \t </div>\r\n");
      out.write("           </div>\r\n");
      out.write("          <article class=\"grid_4\">\r\n");
      out.write("            <h3>Otras Opciones</h3>\r\n");
      out.write("            <ul class=\"list-1\">\r\n");
      out.write("              <li>Conocer el IMC</li>\r\n");
      out.write("              <form method =\"get\" action = \"ProcesoControlador\">\r\n");
      out.write("              <span class=\"text-form\"></span><span class=\"border\">\r\n");
      out.write("                  <input type=\"text\" placeholder = \"Talla\" name = \"talla\">\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <span class=\"text-form\"></span><span class=\"border\">\r\n");
      out.write("                  <input type=\"text\" placeholder = \"Peso\" name = \"peso\">\r\n");
      out.write("                  </span>\r\n");
      out.write("                  <br></br>\r\n");
      out.write("      \t\t\t  <button type=\"submit\" name=\"formulario\" value=\"imc\" class=\"button-2\">Resultado</button>\r\n");
      out.write("      \t\t\t  <span class=\"text-form\"></span><span class=\"border\">\r\n");
      out.write("                  <input type=\"text\" name=\"resultado\" value=\"");
 if (request.getAttribute("resultado")!= null)out.println(request.getAttribute("resultado"));else out.println(" "); 
      out.write("\" disabled=\"disabled\" />\r\n");
      out.write("                  </span>\r\n");
      out.write("              </form>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </article>\r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  </header>\r\n");
      out.write("</div>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
